import = ["~/.config/alacritty/themes/catppuccin-latte.toml"]

[shell]
program = "/opt/zellij/zellij"

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true

[font]
size = 14
normal = { family = "Monaspace Neon" }
bold = { family = "Monaspace Neon" }
italic = { family = "Monaspace Radon", style = "Bold" }
bold_italic= { family = "Monaspace Radon" }
offset.y = 2
