import = ["~/.config/alacritty/themes/tokyonight-moon.toml"]

[shell]
program = "tmux"

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true
opacity = 0.8
blur = true

[font]
size = 14
normal = { family = "Monaspace Neon" }
bold = { family = "Monaspace Neon" }
italic = { family = "Monaspace Radon", style = "Regular" }
bold_italic = { family = "Monaspace Radon", style = "Bold" }
offset.y = 2

[selection]
save_to_clipboard = true
