import = ["~/.config/alacritty/themes/tokyonight-moon.toml"]

[shell]
program = "/bin/zsh"
# This starts tmux and falls back to an hard coded path when not found. This
# happens on osX with homebrew for some reason.
args = ["-c", "tmux || /usr/local/bin/tmux"] 

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true

[font]
size = 14
normal = { family = "MonaspiceAr Nerd Font" }
bold = { family = "MonaspiceAr Nerd Font", style = "Bold" }
italic = { family = "MonaspiceRn Nerd Font", style = "Regular" }
bold_italic = { family = "MonaspiceRn Nerd Font", style = "Bold" }
offset.y = 2

[selection]
save_to_clipboard = true
