import = ["~/.config/alacritty/themes/melange.toml"]

[shell]
program = "/bin/tmux"

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true

[font]
size = 14
normal = { family = "Monaspace Neon Var" }
bold = { family = "Monaspace Neon Var" }
italic = { family = "Monaspace Radon Var", style = "Bold" }
bold_italic = { family = "Monaspace Radon Var" }
offset.y = 2

[selection]
save_to_clipboard = true
