import = ["~/.config/alacritty/themes/catppuccin-latte.toml"]

[shell]
program = "/opt/zellij/zellij"

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true

[font]
size = 12
normal.family = "Monaspace Neon"
italic.family = "Monaspace Radon"
bold_italic.family = "Monaspace Radon"
