"$schema" = "https://starship.rs/config-schema.json"

format = '''
$gcloud | $kubernetes
$directory$git_branch$git_status$cmd_duration
$character
'''

[directory]
truncate_to_repo = false

[gcloud]
format = '[$symbol$project]($style)'

[kubernetes]
disabled = false
format = '[$symbol$context]($style)'

[cmd_duration]
format = '[last command took [$duration]($style)](italic)'
style = 'bold italic yellow'
