[settings]
minimum_release_age = "7d"

[tools]
rust = "latest"
cargo-dist = "latest"
go = "latest"
node = "latest"

# Generic tools
"github:tree-sitter/tree-sitter" = "latest"

# LSP's
"aqua:lua-language-server" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"pipx:python-lsp-server" = "latest"
