[tools]
node = "latest"
rust = "latest"
cargo = "latest"
go = "latest"
pnpm = "latest"
uv = "latest"

# Generic tools
"github:neovim/neovim" = "0.12"
"github:tree-sitter/tree-sitter" = "latest"
"github:casey/just" = "latest"

# LSP's
"aqua:lua-language-server" = "latest"
"aqua:terraform-ls" = "latest"
"cargo:just-lsp" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:@typescript/native-preview" = "latest"
"npm:vscode-json-languageservice" = "latest"

[tools."http:yaml-language-server"]
version = "1.21.0"
url = "https://github.com/redhat-developer/yaml-language-server/archive/refs/tags/{{version}}.zip"
postinstall = '''
    cd $MISE_TOOL_INSTALL_PATH;
    npm install;
    npm run build;
    cd -;
'''

# Formatters and linters
"npm:prettier" = "latest"
"cargo:stylua" = "latest"

# Java and kotlin stuff that need special attention
[tools."http:kotlin-lsp"]
version = "262.2310.0"
url = "https://download-cdn.jetbrains.com/kotlin-lsp/{{version}}/kotlin-lsp-{{version}}-{{os()}}-{{arch()}}.zip"
postinstall = '''
    mkdir $MISE_TOOL_INSTALL_PATH/bin;
    ln -s "$MISE_TOOL_INSTALL_PATH/kotlin-lsp.sh" "$MISE_TOOL_INSTALL_PATH/bin/kotlin-lsp";
    chmod +x "$MISE_TOOL_INSTALL_PATH/kotlin-lsp.sh";
'''

[tools."github:facebook/ktfmt"]
version = "latest"
asset_pattern = "ktfmt-*-with-dependencies.jar"
postinstall = '''
    mkdir $MISE_TOOL_INSTALL_PATH/bin;
    echo "#!/bin/bash" > $MISE_TOOL_INSTALL_PATH/bin/ktfmt
    echo "java -jar $MISE_TOOL_INSTALL_PATH/ktfmt-${MISE_TOOL_VERSION}-with-dependencies.jar \$@" >> $MISE_TOOL_INSTALL_PATH/bin/ktfmt
    chmod +x "$MISE_TOOL_INSTALL_PATH/bin/ktfmt"
'''

[tools."github:detekt/detekt"]
version = "latest"
asset_pattern = "detekt-cli-*-all.jar"
postinstall = '''
    mkdir $MISE_TOOL_INSTALL_PATH/bin
    echo "#!/bin/bash" > $MISE_TOOL_INSTALL_PATH/bin/detekt
    echo "java -jar $MISE_TOOL_INSTALL_PATH/detekt-cli-${MISE_TOOL_VERSION}-all.jar \$@" >> $MISE_TOOL_INSTALL_PATH/bin/detekt
    chmod +x "$MISE_TOOL_INSTALL_PATH/bin/detekt"
'''
