[colors.primary]
background = "#FFFCF0"
foreground = "#100F0F"
dim_foreground = "#100F0F"
bright_foreground = "#100F0F"

[colors.cursor]
text = "#FFFCF0"
cursor = "#100F0F"

[colors.normal]
black = "#100F0F"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
blue = "#4385BE"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#FFFCF0"

[colors.bright]
black = "#100F0F"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
blue = "#4385BE"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#FFFCF0"

[colors.dim]
black = "#100F0F"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
blue = "#4385BE"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#FFFCF0"

