-- Init
require("plugins")
require("general")
require("keys")
require("plugins.treesitter")
require("plugins.mason")
require("plugins.cmp")
require("plugins.null_ls")
require("plugins.copilot")
require("plugins.dap")
