require("settings")
require("keybinds")
require("statusline")
require("diagnostics")
require("lsp")

-- Install all the needed plugins
require("plugins.catppuccin")
require("plugins.conform")
require("plugins.dap")
require("plugins.detekt")
require("plugins.mason")
require("plugins.neogit")
require("plugins.oil")
require("plugins.quicker")
require("plugins.snacks")
require("plugins.treesitter")
